from infscale.configs.controller import ReqGenEnum
from infscale.configs.job import ServeConfig

inspector_test_cases = [
    # no suspended worlds
    (
        ServeConfig(
            job_id="job1",
            reqgen_config={"sort": ReqGenEnum.DEFAULT, "params": None},
            name="test",
            model="model",
            dataset={"path": "", "name": "", "split": ""},
            stage={ "id": "s-0", "start": -1, "end": -1},
            workers_stage_info={},
            flow_graph={
                "s-0": [{"name": "w0", "peers": ["0-0"]}],
                "0-0": [{"name": "w1", "peers": ["1-0"]}],
                "1-0": [{"name": "w2", "peers": ["s-0"]}],
            },
        ),
        set(),
        set()
    ),
    # I'm s-0, 0-0 failed, 
    (
        ServeConfig(
            job_id="job1",
            reqgen_config={"sort": ReqGenEnum.DEFAULT, "params": None},
            name="test",
            model="model",
            dataset={"path": "", "name": "", "split": ""},
            stage={ "id": "s-0", "start": -1, "end": -1},
            workers_stage_info={},
            flow_graph={
                "s-0": [{"name": "w0", "peers": ["1-0"]}],
                "0-0": [{"name": "w1", "peers": ["s-0"]}],
                "0-1": [{"name": "w2", "peers": ["s-0"]}],
                "1-0": [{"name": "w3", "peers": ["0-0"]}, {"name": "w4", "peers": ["0-1"]}],
            },
        ),
        {"0-0"},
        set(),
    ),
    # I'm s-0, 1-0 failed, 
    (
        ServeConfig(
            job_id="job1",
            reqgen_config={"sort": ReqGenEnum.DEFAULT, "params": None},
            name="test",
            model="model",
            dataset={"path": "", "name": "", "split": ""},
            stage={ "id": "s-0", "start": -1, "end": -1},
            workers_stage_info={},
            flow_graph={
                "s-0": [{"name": "w0", "peers": ["2-0"]}],
                "0-0": [{"name": "w1", "peers": ["s-0"]}],
                "0-1": [{"name": "w2", "peers": ["s-0"]}],
                "1-0": [{"name": "w3", "peers": ["0-0"]}],
                "1-1": [{"name": "w4", "peers": ["0-1"]}],
                "2-0": [{"name": "w5", "peers": ["1-0"]}, {"name": "w6", "peers": ["1-1"]}],
            },
        ),
        {"1-0"},
        {"w1"},
    ),
    # I'm 0-0, 1-0 failed, 
    (
        ServeConfig(
            job_id="job1",
            reqgen_config={"sort": ReqGenEnum.DEFAULT, "params": None},
            name="test",
            model="model",
            dataset={"path": "", "name": "", "split": ""},
            stage={ "id": "0-0", "start": 0, "end": 15},
            workers_stage_info={},
            flow_graph={
                "s-0": [{"name": "w0", "peers": ["2-0"]}],
                "0-0": [{"name": "w1", "peers": ["s-0"]}],
                "0-1": [{"name": "w2", "peers": ["s-0"]}],
                "1-0": [{"name": "w3", "peers": ["0-0"]}],
                "1-1": [{"name": "w4", "peers": ["0-1"]}],
                "2-0": [{"name": "w5", "peers": ["1-0"]}, {"name": "w6", "peers": ["1-1"]}],
            },
        ),
        {"1-0"},
        set(),
    ),
    # I'm 2-0, 1-0 failed, 
    (
        ServeConfig(
            job_id="job1",
            reqgen_config={"sort": ReqGenEnum.DEFAULT, "params": None},
            name="test",
            model="model",
            dataset={"path": "", "name": "", "split": ""},
            stage={ "id": "2-0", "start": 33, "end": 54},
            workers_stage_info={},
            flow_graph={
                "s-0": [{"name": "w0", "peers": ["2-0"]}],
                "0-0": [{"name": "w1", "peers": ["s-0"]}],
                "0-1": [{"name": "w2", "peers": ["s-0"]}],
                "1-0": [{"name": "w3", "peers": ["0-0"]}],
                "1-1": [{"name": "w4", "peers": ["0-1"]}],
                "2-0": [{"name": "w5", "peers": ["1-0"]}, {"name": "w6", "peers": ["1-1"]}],
            },
        ),
        {"1-0"},
        set(),
    ),
    # I'm 0-1, 1-0 failed, 
    (
        ServeConfig(
            job_id="job1",
            reqgen_config={"sort": ReqGenEnum.DEFAULT, "params": None},
            name="test",
            model="model",
            dataset={"path": "", "name": "", "split": ""},
            stage={ "id": "0-1", "start": 0, "end": 15},
            workers_stage_info={},
            flow_graph={
                "s-0": [{"name": "w0", "peers": ["2-0"]}],
                "0-0": [{"name": "w1", "peers": ["s-0"]}],
                "0-1": [{"name": "w2", "peers": ["s-0"]}],
                "1-0": [{"name": "w3", "peers": ["0-0"]}],
                "1-1": [{"name": "w4", "peers": ["0-1"]}],
                "2-0": [{"name": "w5", "peers": ["1-0"]}, {"name": "w6", "peers": ["1-1"]}],
            },
        ),
        {"1-0"},
        set(),
    ),
    # I'm 1-1, 1-0 failed, 
    (
        ServeConfig(
            job_id="job1",
            reqgen_config={"sort": ReqGenEnum.DEFAULT, "params": None},
            name="test",
            model="model",
            dataset={"path": "", "name": "", "split": ""},
            stage={ "id": "1-1", "start": 16, "end": 32},
            workers_stage_info={},
            flow_graph={
                "s-0": [{"name": "w0", "peers": ["2-0"]}],
                "0-0": [{"name": "w1", "peers": ["s-0"]}],
                "0-1": [{"name": "w2", "peers": ["s-0"]}],
                "1-0": [{"name": "w3", "peers": ["0-0"]}],
                "1-1": [{"name": "w4", "peers": ["0-1"]}],
                "2-0": [{"name": "w5", "peers": ["1-0"]}, {"name": "w6", "peers": ["1-1"]}],
            },
        ),
        {"1-0"},
        set(),
    ),
    # I'm s-0, 1-1 failed, 
    (
        ServeConfig(
            job_id="job1",
            reqgen_config={"sort": ReqGenEnum.DEFAULT, "params": None},
            name="test",
            model="model",
            dataset={"path": "", "name": "", "split": ""},
            stage={ "id": "s-0", "start": -1, "end": -1},
            workers_stage_info={},
            flow_graph={
                "s-0": [{"name": "w0", "peers": ["2-0"]}],
                "0-0": [{"name": "w1", "peers": ["s-0"]}],
                "0-1": [{"name": "w2", "peers": ["s-0"]}],
                "1-0": [{"name": "w3", "peers": ["0-0"]}],
                "1-1": [{"name": "w4", "peers": ["0-1"]}],
                "2-0": [{"name": "w5", "peers": ["1-0"]}, {"name": "w6", "peers": ["1-1"]}],
            },
        ),
        {"1-1"},
        {"w2"},
    ),
    # I'm 0-1, 1-1 failed, 
    (
        ServeConfig(
            job_id="job1",
            reqgen_config={"sort": ReqGenEnum.DEFAULT, "params": None},
            name="test",
            model="model",
            dataset={"path": "", "name": "", "split": ""},
            stage={ "id": "0-1", "start": 0, "end": 15},
            workers_stage_info={},
            flow_graph={
                "s-0": [{"name": "w0", "peers": ["2-0"]}],
                "0-0": [{"name": "w1", "peers": ["s-0"]}],
                "0-1": [{"name": "w2", "peers": ["s-0"]}],
                "1-0": [{"name": "w3", "peers": ["0-0"]}],
                "1-1": [{"name": "w4", "peers": ["0-1"]}],
                "2-0": [{"name": "w5", "peers": ["1-0"]}, {"name": "w6", "peers": ["1-1"]}],
            },
        ),
        {"1-1"},
        set(),
    ),
    # I'm s-0, 2-0 failed, 
    (
        ServeConfig(
            job_id="job1",
            reqgen_config={"sort": ReqGenEnum.DEFAULT, "params": None},
            name="test",
            model="model",
            dataset={"path": "", "name": "", "split": ""},
            stage={ "id": "s-0", "start": -1, "end": -1},
            workers_stage_info={},
            flow_graph={
                "s-0": [{"name": "w0", "peers": ["2-0"]}],
                "0-0": [{"name": "w1", "peers": ["s-0"]}],
                "0-1": [{"name": "w2", "peers": ["s-0"]}],
                "1-0": [{"name": "w3", "peers": ["0-0"]}],
                "1-1": [{"name": "w4", "peers": ["0-1"]}],
                "2-0": [{"name": "w5", "peers": ["1-0"]}, {"name": "w6", "peers": ["1-1"]}],
            },
        ),
        {"2-0"},
        {"w1", "w2"},
    ),
    # I'm 0-0, 2-0 failed, 
    (
        ServeConfig(
            job_id="job1",
            reqgen_config={"sort": ReqGenEnum.DEFAULT, "params": None},
            name="test",
            model="model",
            dataset={"path": "", "name": "", "split": ""},
            stage={ "id": "0-0", "start": 0, "end": 15},
            workers_stage_info={},
            flow_graph={
                "s-0": [{"name": "w0", "peers": ["2-0"]}],
                "0-0": [{"name": "w1", "peers": ["s-0"]}],
                "0-1": [{"name": "w2", "peers": ["s-0"]}],
                "1-0": [{"name": "w3", "peers": ["0-0"]}],
                "1-1": [{"name": "w4", "peers": ["0-1"]}],
                "2-0": [{"name": "w5", "peers": ["1-0"]}, {"name": "w6", "peers": ["1-1"]}],
            },
        ),
        {"2-0"},
        {"w3"},
    ),
    # I'm 1-0, 2-0 failed, 
    (
        ServeConfig(
            job_id="job1",
            reqgen_config={"sort": ReqGenEnum.DEFAULT, "params": None},
            name="test",
            model="model",
            dataset={"path": "", "name": "", "split": ""},
            stage={ "id": "1-0", "start": 16, "end": 32},
            workers_stage_info={},
            flow_graph={
                "s-0": [{"name": "w0", "peers": ["2-0"]}],
                "0-0": [{"name": "w1", "peers": ["s-0"]}],
                "0-1": [{"name": "w2", "peers": ["s-0"]}],
                "1-0": [{"name": "w3", "peers": ["0-0"]}],
                "1-1": [{"name": "w4", "peers": ["0-1"]}],
                "2-0": [{"name": "w5", "peers": ["1-0"]}, {"name": "w6", "peers": ["1-1"]}],
            },
        ),
        {"2-0"},
        set(),
    ),
    # I'm 0-1, 2-0 failed, 
    (
        ServeConfig(
            job_id="job1",
            reqgen_config={"sort": ReqGenEnum.DEFAULT, "params": None},
            name="test",
            model="model",
            dataset={"path": "", "name": "", "split": ""},
            stage={ "id": "0-1", "start": 0, "end": 15},
            workers_stage_info={},
            flow_graph={
                "s-0": [{"name": "w0", "peers": ["2-0"]}],
                "0-0": [{"name": "w1", "peers": ["s-0"]}],
                "0-1": [{"name": "w2", "peers": ["s-0"]}],
                "1-0": [{"name": "w3", "peers": ["0-0"]}],
                "1-1": [{"name": "w4", "peers": ["0-1"]}],
                "2-0": [{"name": "w5", "peers": ["1-0"]}, {"name": "w6", "peers": ["1-1"]}],
            },
        ),
        {"2-0"},
        {"w4"},
    ),
    # I'm 1-1, 2-0 failed, 
    (
        ServeConfig(
            job_id="job1",
            reqgen_config={"sort": ReqGenEnum.DEFAULT, "params": None},
            name="test",
            model="model",
            dataset={"path": "", "name": "", "split": ""},
            stage={ "id": "1-1", "start": 16, "end": 32},
            workers_stage_info={},
            flow_graph={
                "s-0": [{"name": "w0", "peers": ["2-0"]}],
                "0-0": [{"name": "w1", "peers": ["s-0"]}],
                "0-1": [{"name": "w2", "peers": ["s-0"]}],
                "1-0": [{"name": "w3", "peers": ["0-0"]}],
                "1-1": [{"name": "w4", "peers": ["0-1"]}],
                "2-0": [{"name": "w5", "peers": ["1-0"]}, {"name": "w6", "peers": ["1-1"]}],
            },
        ),
        {"2-0"},
        set(),
    ),
    # I'm s-0, 2-0 failed, 
    (
        ServeConfig(
            job_id="job1",
            reqgen_config={"sort": ReqGenEnum.DEFAULT, "params": None},
            name="test",
            model="model",
            dataset={"path": "", "name": "", "split": ""},
            stage={ "id": "s-0", "start": 16, "end": 32},
            workers_stage_info={},
            flow_graph={
                "s-0": [{"name": "w0", "peers": ["2-0"]}],
                "0-0": [{"name": "w1", "peers": ["s-0"]}],
                "0-1": [{"name": "w2", "peers": ["s-0"]}],
                "1-0": [{"name": "w3", "peers": ["0-0"]}],
                "1-1": [{"name": "w4", "peers": ["0-1"]}],
                "2-0": [{"name": "w5", "peers": ["1-0"]}, {"name": "w6", "peers": ["1-1"]}],
            },
        ),
        {"2-0"},
        {"w1", "w2"},
    ),
    # I'm s-0, 1-0 and 1-1 failed, 
    (
        ServeConfig(
            job_id="job1",
            reqgen_config={"sort": ReqGenEnum.DEFAULT, "params": None},
            name="test",
            model="model",
            dataset={"path": "", "name": "", "split": ""},
            stage={ "id": "s-0", "start": 16, "end": 32},
            workers_stage_info={},
            flow_graph={
                "s-0": [{"name": "w0", "peers": ["2-0"]}],
                "0-0": [{"name": "w1", "peers": ["s-0"]}],
                "0-1": [{"name": "w2", "peers": ["s-0"]}],
                "1-0": [{"name": "w3", "peers": ["0-0"]}, {"name": "w8", "peers": ["0-1"]}],
                "1-1": [{"name": "w4", "peers": ["0-1"]}, {"name": "w7", "peers": ["0-0"]}],
                "2-0": [{"name": "w5", "peers": ["1-0"]}, {"name": "w6", "peers": ["1-1"]}],
            },
        ),
        {"1-0", "1-1"},
        {"w1", "w2"},
    ),
    # LLM - I'm s-0, 2-0 failed, 
    (
        ServeConfig(
            job_id="job1",
            reqgen_config={"sort": ReqGenEnum.DEFAULT, "params": None},
            name="test",
            model="model",
            dataset={"path": "", "name": "", "split": ""},
            stage={ "id": "s-0", "start": 16, "end": 32},
            workers_stage_info={},
            flow_graph={
                "s-0": [{"name": "w0", "peers": ["2-0"]}],
                "0-0": [{"name": "w1", "peers": ["s-0"]}, {"name": "w2", "peers": ["2-0"]}],
                "1-0": [{"name": "w3", "peers": ["0-0"]}],
                "2-0": [{"name": "w4", "peers": ["1-0"]}],
            },
        ),
        {"2-0"},
        {"w1"},
    ),
    # LLM - I'm s-0, 1-0 failed, 
    (
        ServeConfig(
            job_id="job1",
            reqgen_config={"sort": ReqGenEnum.DEFAULT, "params": None},
            name="test",
            model="model",
            dataset={"path": "", "name": "", "split": ""},
            stage={ "id": "s-0", "start": 16, "end": 32},
            workers_stage_info={},
            flow_graph={
                "s-0": [{"name": "w0", "peers": ["2-0"]}],
                "0-0": [{"name": "w1", "peers": ["s-0"]}, {"name": "w2", "peers": ["2-0"]}],
                "1-0": [{"name": "w3", "peers": ["0-0"]}],
                "2-0": [{"name": "w4", "peers": ["1-0"]}],
            },
        ),
        {"1-0"},
        {"w1"},
    ),
    # LLM - I'm 0-0, 2-0 failed, 
    (
        ServeConfig(
            job_id="job1",
            reqgen_config={"sort": ReqGenEnum.DEFAULT, "params": None},
            name="test",
            model="model",
            dataset={"path": "", "name": "", "split": ""},
            stage={ "id": "0-0", "start": 16, "end": 32},
            workers_stage_info={},
            flow_graph={
                "s-0": [{"name": "w0", "peers": ["2-0"]}],
                "0-0": [{"name": "w1", "peers": ["s-0"]}, {"name": "w2", "peers": ["2-0"]}],
                "1-0": [{"name": "w3", "peers": ["0-0"]}],
                "2-0": [{"name": "w4", "peers": ["1-0"]}],
            },
        ),
        {"2-0"},
        {"w3"},
    ),
]
