# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: management.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10management.proto\x12\nmanagement\x1a\x1bgoogle/protobuf/empty.proto\"\x15\n\x07\x41gentID\x12\n\n\x02id\x18\x01 \x01(\t\"\x14\n\x06RegReq\x12\n\n\x02id\x18\x01 \x01(\t\"(\n\x06RegRes\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\"%\n\x06Status\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"\x1b\n\x08Manifest\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x32\xf3\x01\n\x0fManagementRoute\x12\x34\n\x08register\x12\x12.management.RegReq\x1a\x12.management.RegRes\"\x00\x12:\n\theartbeat\x12\x13.management.AgentID\x1a\x16.google.protobuf.Empty\"\x00\x12\x36\n\x06update\x12\x12.management.Status\x1a\x16.google.protobuf.Empty\"\x00\x12\x36\n\x05\x66\x65tch\x12\x13.management.AgentID\x1a\x14.management.Manifest\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'management_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AGENTID']._serialized_start=61
  _globals['_AGENTID']._serialized_end=82
  _globals['_REGREQ']._serialized_start=84
  _globals['_REGREQ']._serialized_end=104
  _globals['_REGRES']._serialized_start=106
  _globals['_REGRES']._serialized_end=146
  _globals['_STATUS']._serialized_start=148
  _globals['_STATUS']._serialized_end=185
  _globals['_MANIFEST']._serialized_start=187
  _globals['_MANIFEST']._serialized_end=214
  _globals['_MANAGEMENTROUTE']._serialized_start=217
  _globals['_MANAGEMENTROUTE']._serialized_end=460
# @@protoc_insertion_point(module_scope)
