- name: poll job status
  hosts: cisco-research-7
  gather_facts: false
  tasks:
    - name: check endpoint health and if job exists
      uri:
        url: http://127.0.0.1:8080/job/job1
        method: GET
        return_content: yes
        timeout: 3
      register: precheck
      failed_when: precheck.status == -1 or precheck.status == 404

    - name: poll job status endpoint until "complete" or "failed" is returned
      uri:
        url: http://127.0.0.1:8080/job/job1
        method: GET
        return_content: yes
        timeout: 3
      register: job_status
      until: job_status.content | regex_replace('"', '') in ['complete', 'failed']
      retries: 12  # (12 * 5 seconds = 60 seconds)
      delay: 5  # delay between retries in seconds
